version: '3.8'
services:
  app:
    build: .
    # existing PHP app service settings
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
